# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WINMOLAnalyzer

                                 A QGIS plugin
 Plugin to detect stems from UAV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by Hochschule für nachhaltige Entwicklung Eberswalde | mundialis GmbH & Co. KG | terrestris GmbH & Co. KG
        email                : Stefan.Reder@hnee.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load the WINMOLAnalyzer plugin.

    The compute environment (onnxruntime + geo stack; NO TensorFlow) is
    resolved/created here, but NEVER fatally: a declined or failed setup logs
    a message and still loads the plugin, so QGIS is never left with a "broken
    plugin". The dialog re-checks readiness before running and offers a retry.

    :param iface: A QGIS interface instance.
    """
    # Imported here (not at module top) so the package stays importable outside
    # QGIS -- e.g. under pytest -- where the QGIS-only deps are unavailable.
    from .plugin_utils.installer import resolve_environment

    plugin_dir = os.path.dirname(__file__)
    # build=False: never download Python / build the venv on the QGIS load
    # thread (that could take minutes and freeze startup). Just report
    # readiness; the dialog builds the environment asynchronously if needed.
    env = resolve_environment(plugin_dir, prompt=False, build=False)

    try:
        from qgis.core import Qgis, QgsMessageLog
        level = Qgis.Info if env.get("python") else Qgis.Warning
        QgsMessageLog.logMessage(env.get("message", ""), "WINMOL", level)
    except Exception:
        pass

    from .winmol_analyzer import WINMOLAnalyzer
    return WINMOLAnalyzer(iface, env)
