# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WINMOLAnalyzer

                                 A QGIS plugin
 Plugin to detect stems from UAV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by Hochschule für nachhaltige Entwicklung Eberswalde | mundialis GmbH & Co. KG | terrestris GmbH & Co. KG
        email                : Stefan.Reder@hnee.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import site
import sys


def _add_venv_site_packages(venv_path: str) -> None:
    """Make venv-installed packages importable from within QGIS' Python.

    Dependencies are installed into the plugin's internal venv, but QGIS runs
    its own Python interpreter. We therefore need to add the venv's
    site-packages directory to sys.path before importing plugin modules that
    depend on those packages.
    """

    if not venv_path:
        return

    if sys.platform == "win32":
        sp = os.path.join(venv_path, "Lib", "site-packages")
        scripts = os.path.join(venv_path, "Scripts")
        if os.path.isdir(scripts):
            try:
                os.add_dll_directory(scripts)
            except Exception:
                # Best-effort; missing this should not stop the plugin.
                pass
    else:
        pyver = f"python{sys.version_info.major}.{sys.version_info.minor}"
        sp = os.path.join(venv_path, "lib", pyver, "site-packages")

    if os.path.isdir(sp):
        site.addsitedir(sp)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WINMOLAnalyzer
 class from file WINMOLAnalyzer
.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Imported here (not at module top) so the package stays importable outside
    # QGIS -- e.g. under pytest -- where these QGIS-only deps are unavailable.
    from .plugin_utils.installer import WINMOL_VENV_NAME, \
        ensure_venv, ensure_dependencies

    project_path = os.path.dirname(__file__)

    venv_path = ensure_venv(
        os.path.join(
            project_path,
            WINMOL_VENV_NAME
        )
    )
    ensure_dependencies(venv_path)

    # Make packages from the internal venv importable in QGIS' Python.
    _add_venv_site_packages(venv_path)

    from .winmol_analyzer import WINMOLAnalyzer
    return WINMOLAnalyzer(iface, venv_path)
