# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WINMOLAnalyzer

                                 A QGIS plugin
 Plugin to detect stems from UAV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by Hochschule für nachhaltige Entwicklung Eberswalde | mundialis GmbH & Co. KG | terrestris GmbH & Co. KG
        email                : Stefan.Reder@hnee.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os

from .plugin_utils.installer import resolve_environment


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WINMOLAnalyzer
 class from file WINMOLAnalyzer
.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    plugin_dir = os.path.dirname(__file__)

    # Never builds/blocks at QGIS load: a missing environment comes back
    # as status 'needs_setup' and is built off the GUI thread on first
    # Run (see tasks_threads.EnvSetupWorker). The compute env runs as a
    # separate child process (see plugin_utils/childenv.py), so nothing
    # from it is ever imported into QGIS' own interpreter.
    env = resolve_environment(plugin_dir)

    from .winmol_analyzer import WINMOLAnalyzer
    return WINMOLAnalyzer(iface, env)
