# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WINMOLAnalyzer

                                 A QGIS plugin
 Plugin to detect stems from UAV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-29
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Hochschule für nachhaltige Entwicklung Eberswalde | mundialis GmbH & Co. KG | terrestris GmbH & Co. KG
        email                : Stefan.Reder@hnee.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources (optional): the compiled resources.py is PyQt5-format
# and may not load under Qt6/QGIS 4. Icons fall back to the icon.png file, so a
# failure here is cosmetic, not fatal.
try:
    from .resources import *  # noqa: F401,F403
except Exception:
    pass

# Import the code for the dialog
from .winmol_analyzer_dialog import WINMOLAnalyzerDialog


class WINMOLAnalyzer:
    """QGIS Plugin Implementation."""

    env = None

    def __init__(self, iface, env):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # Initialize locale. This runs inside __init__, which classFactory
        # calls, so ANY exception here stops the plugin loading at all — no
        # toolbar icon, no menu, nothing to recover from. QSettings.value()
        # returns None for a missing key, and the previous `[0:2]` on that
        # raised TypeError on profiles where 'locale/userLocale' is unset.
        # There is no i18n directory in this repo and none is packaged, so a
        # translation can never load; the whole block is best-effort.
        try:
            locale = str(QSettings().value('locale/userLocale', '') or '')[0:2]
            locale_path = os.path.join(
                self.plugin_dir,
                'i18n',
                'WINMOLAnalyze_{}.qm'.format(locale))

            if locale and os.path.exists(locale_path):
                self.translator = QTranslator()
                self.translator.load(locale_path)
                QCoreApplication.installTranslator(self.translator)
        except Exception:  # noqa: BLE001 - never block plugin load
            pass

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&WINMOL Analyzer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.env = env

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('WINMOLAnalyzer', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # Load from the file (works on Qt5 and Qt6) rather than the compiled
        # ':/plugins/...' resource, which is PyQt5-format.
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Detects stems from UAV images'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Stop any running background threads BEFORE QGIS drops the dialog
        # reference: destroying a still-running QThread (e.g. unloading/
        # reloading the plugin mid-run) triggers Qt's qFatal() and aborts
        # all of QGIS.
        dlg = getattr(self, "dlg", None)
        if dlg is not None and hasattr(dlg, "_shutdown_threads"):
            try:
                dlg._shutdown_threads()
            except Exception:
                pass
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&WINMOL Analyzer'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when
        # the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = WINMOLAnalyzerDialog(None, self.env)

        # show the dialog
        self.dlg.show()
