# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WINMOLAnalyzer
Dialog
                                 A QGIS plugin
 Plugin to detect stems from UAV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Hochschule für nachhaltige Entwicklung Eberswalde | mundialis GmbH & Co. KG | terrestris GmbH & Co. KG
        email                : Stefan.Reder@hnee.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import glob
import json
from pathlib import Path

try:
    import psutil          # optional: used only to report available RAM
except Exception:
    psutil = None

# qgis.PyQt shims to the active Qt binding (PyQt5 on QGIS 3, PyQt6 on QGIS 4).
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.PyQt.QtCore import QThread, QTimer
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsRasterLayer, QgsSettings)
from qgis.PyQt import QtWidgets, uic

from .classes.Config import Config
from .plugin_utils import installer
from .tasks_threads import Worker

current_path = os.path.dirname(__file__)

# Keep-alive for background threads that outlive the dialog. A parentless
# QThread whose only Python reference is a dialog attribute gets GC-deleted when
# the dialog is torn down (QGIS quit, plugin unload/reload) — and destroying a
# QThread while its OS thread still runs triggers Qt's qFatal() -> abort(),
# taking down all of QGIS. If a thread can't be stopped promptly at teardown we
# stash it here (module scope survives dialog GC) so it is never collected while
# running; it self-evicts on finished().
_ALIVE_BG = set()

# This loads your .ui file so that PyQt can populate your plugin with the
# elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(current_path, "winmol_analyzer_dialog_base.ui")
)


class WINMOLAnalyzerDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None, env=None):
        """Constructor. `env` is the dict from installer.resolve_environment
        ({'python': <exe>, 'venv_path': <path>, ...})."""
        super(WINMOLAnalyzerDialog, self).__init__(parent)
        self.setupUi(self)
        # Derived outputs are auto-generated from the stem map output path.
        # Keep these fields visible for transparency, but prevent manual editing.
        try:
            self.output_lineEdit_trees.setReadOnly(True)
            self.output_lineEdit_nodes.setReadOnly(True)
            self.output_toolButton_trees.setEnabled(False)
            self.output_toolButton_nodes.setEnabled(False)
            # Output is optional now: empty -> temp folder, then Export.
            self.output_lineEdit_stem.setPlaceholderText(
                "optional — leave empty to use a temp folder, then Export…")
        except Exception:
            pass
        self._updating_output_fields = False

        # Set the initial title
        self.setWindowTitle("WINMOL Analyzer")

        # parameters
        self.uav_path = ""
        self.model_path = ""
        self.stem_path = ""
        self.trees_path = ""
        self.process_type = "Stems"

        self.uav_layer_path = None
        self.uav_layer_name = None
        self.crs = None
        self.worker = None
        self.thread = None
        # Background environment-build thread (download 3.11 + venv + pip).
        self._env_thread = None
        self._env_worker = None
        # Re-entrancy guard: reassigning self.thread while its OS thread is
        # still running destroys a live QThread -> Qt qFatal() -> the whole
        # QGIS process aborts. Never start a second run over a live one.
        self._run_active = False
        # Outputs of the last successful run, for the Export action. Each entry
        # is an absolute path (stem map + optional gpkg).
        self._last_outputs = []
        # If True, the stem map went to a temp dir and should be offered for
        # export (the user didn't choose a permanent output path).
        self._last_output_is_temp = False

        # Create a Config instance
        self.config = Config()

        self.set_connections()
        self.output_log.setReadOnly(True)
        # A verbose env build streams thousands of pip lines through here;
        # cap the scrollback so the widget can't grow without bound.
        try:
            self.output_log.setMaximumBlockCount(5000)
        except Exception:
            pass
        self.env = env or {}
        self.python_exe = self.env.get("python")
        # models live next to the plugin. Derive from this file's location --
        # NOT from venv_path, which may now live outside the plugin dir (in the
        # QGIS profile) so that uninstalling the plugin can't fail on it.
        plugin_dir = os.path.dirname(os.path.abspath(__file__))
        self.models_dir = os.path.join(plugin_dir, "models")
        self.populate_model_combo_box()
        # Controls that aren't in the .ui: persistent Environment button +
        # a QGIS layer selector for the input raster.
        self._add_custom_controls()
        # If no usable interpreter yet, offer the environment picker once the
        # dialog is visible (deferred so it doesn't block construction).
        if not self._env_ready():
            QTimer.singleShot(0, self.choose_environment)
        self.process_type = None

        # Nodes output uses the Trees output path (no separate file/path field).
        # Hide/disable the old nodes output widgets if they exist in the .ui.
        for _wname in ("output_lineEdit_nodes", "output_toolButton_nodes"):
            _w = getattr(self, _wname, None)
            if _w is not None:
                _w.hide()
                _w.setEnabled(False)

        # hide warning label
        self.uav_warning_label.hide()

    def set_connections(self):
        self.run_button.clicked.connect(self.run_process)
        self.model_comboBox.currentIndexChanged.connect(
            self.handle_model_combo_box_change
        )
        self.set_default_config_parameters()
        self.get_config_parameters_from_gui()
        self.uav_toolButton.clicked.connect(self.file_dialog_uav)
        self.model_toolButton.clicked.connect(self.model_file_dialog)
        self.output_toolButton_stem.clicked.connect(self.file_dialog_stem)
        self.output_lineEdit_stem.textChanged.connect(self._update_derived_output_fields)
        self.output_toolButton_trees.clicked.connect(self.file_dialog_trees)
        self.output_checkBox_stem.stateChanged.connect(self.checkbox_changed_stem)
        self.output_checkBox_trees.stateChanged.connect(self.checkbox_changed_trees)
        self.output_checkBox_nodes.stateChanged.connect(self.checkbox_changed_nodes)
        self.checkbox_changed_stem(2)
        self.checkbox_changed_trees(1)
        self.checkbox_changed_nodes(1)
        self.close_button.clicked.connect(self.close_application)
        self.cancel_button.clicked.connect(self.cancel_process)

    def _log(self, msg: str) -> None:
        """Write a message to the plugin log widget (and stdout as fallback)."""
        try:
            self.output_log.append(str(msg))
        except Exception:
            print(msg)

    def populate_model_combo_box(self) -> None:
        """Fill the model dropdown from config.json.

        config.json is a mapping {"ModelName": "https://.../ModelName.onnx"}.
        The installer downloads these into <plugin>/models/<ModelName>.onnx.

        We always append a "Custom" entry that lets users pick their own
        .onnx (or legacy .hdf5/.keras) file.
        """
        config_path = os.path.join(os.path.dirname(__file__), "config.json")
        model_names = []

        try:
            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            if isinstance(cfg, dict):
                model_names = [k.strip() for k in cfg.keys() if isinstance(k, str) and k.strip()]
        except Exception as e:
            self._log(f"Could not load model list from config.json ({config_path}): {e}")

        try:
            self.model_comboBox.blockSignals(True)
        except Exception:
            pass

        self.model_comboBox.clear()

        if model_names:
            for name in sorted(set(model_names), key=str.lower):
                self.model_comboBox.addItem(name)
        else:
            # Backward-compatible fallback.
            for name in ["Beech", "Spruce", "General"]:
                self.model_comboBox.addItem(name)

        self.model_comboBox.addItem("Custom")

        # Default to Spruce_Deadwood (bundled), then fall back to General.
        for _default in ("Spruce_Deadwood", "General"):
            if model_names and _default in model_names:
                idx = self.model_comboBox.findText(_default)
                if idx >= 0:
                    self.model_comboBox.setCurrentIndex(idx)
                    break

        try:
            self.model_comboBox.blockSignals(False)
        except Exception:
            pass

        self.handle_model_combo_box_change()

    def handle_model_combo_box_change(self):
        selected_text = self.model_comboBox.currentText()
        widgets_to_enable = [
            self.tileside_label,
            self.image_spinBox,
            self.model_lineEdit,
            self.model_toolButton,
            self.segm_label,
            self.tileside_doubleSpinBox,
            self.tileside_unit_label,
            self.image_label,
            self.image_spinBox,
            self.image_unit_label,
        ]

        for widget in widgets_to_enable:
            widget.setEnabled(selected_text == "Custom")

        if selected_text == "Custom":
            self.apply_style_to_line_edit(self.model_lineEdit, True)
        else:
            self.apply_style_to_line_edit(self.model_lineEdit, False)

    def model_file_dialog(self):
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "Select Model File",
            "",
            "Model File (*.onnx *.hdf5 *.keras);;All Files (*)",
            options=options,
        )
        if file_path:
            self.model_lineEdit.setText(file_path)
        self.model_path = self.model_lineEdit.text()

    def set_default_config_parameters(self):
        # set default values
        self.minlength_doubleSpinBox.setValue(self.config.min_length)
        self.maxdistance_doubleSpinBox.setValue(self.config.max_distance)
        self.tolerance_doubleSpinBox.setValue(self.config.tolerance_angle)
        self.maxtree_doubleSpinBox.setValue(self.config.max_tree_height)
        self.tileside_doubleSpinBox.setValue(self.config.tile_size)
        self.image_spinBox.setValue(self.config.img_width)

    def get_config_parameters_from_gui(self):
        self.config.min_length = self.minlength_doubleSpinBox.value()
        self.config.max_distance = self.maxdistance_doubleSpinBox.value()
        self.config.tolerance_angle = self.tolerance_doubleSpinBox.value()
        self.config.max_tree_height = self.maxtree_doubleSpinBox.value()

    def set_crs(self, layer):
        # get crs from uav image
        crs = layer.crs()
        # set crs to config
        self.crs = crs

    def check_input_file(self):
        # get file name of uav image
        file_name = os.path.splitext(os.path.basename(self.uav_path))[0]
        # Load the raster layer
        layer = QgsRasterLayer(self.uav_lineEdit.text(), file_name, "gdal")

        # Check if the layer is valid
        if layer.isValid():

            # set crs
            self.set_crs(layer)

            if not self.crs.isGeographic():  # isGeographic() returns True for unprojected systems like EPSG:4326
                # Enable processing button
                self.run_button.setEnabled(True)
                self.uav_warning_label.hide()  # Hide CRS error if shown before

                # Get the raster's pixel size in map units
                x_pixel_size = layer.rasterUnitsPerPixelX()
                y_pixel_size = layer.rasterUnitsPerPixelY()

                # Convert pixel size to centimeters
                x_pixel_size_cm = x_pixel_size * 100
                y_pixel_size_cm = y_pixel_size * 100

                # Set the threshold for showing the warning label (5 cm)
                threshold_cm = 5

                # Check if either the x or y pixel size exceeds the threshold
                if x_pixel_size_cm > threshold_cm or y_pixel_size_cm > threshold_cm:
                    # show warning label
                    self.uav_warning_label.setText("Warning: Pixel size > 5cm.")
                    self.uav_warning_label.show()
                else:
                    # hide warning label
                    self.uav_warning_label.hide()
            else:
                # Show CRS error and disable processing button
                self.uav_warning_label.setText("Error: Coordinate system is not projected. Please reproject the raster.")
                self.uav_warning_label.show()
                self.run_button.setEnabled(False)
        else:
            print("Invalid raster layer. Check the path and format.")

    def file_dialog_uav(self):
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "Select TIFF File",
            "",
            "TIFF Files (*.tiff *.tif);;All Files (*)",
            options=options,
        )
        if file_path:
            self.uav_lineEdit.setText(file_path)
        # check if pixel size is too large
        self.check_input_file()
        self.uav_path = self.uav_lineEdit.text()

        # Set a sensible default output stem map path (same folder, derived name)
        if self.uav_path and not self.output_lineEdit_stem.text().strip():
            suggested = self._suggest_stem_map_output(self.uav_path)
            if suggested:
                self.output_lineEdit_stem.setText(suggested)

    def file_dialog_stem(self):
        options = QFileDialog.Options()

        # Suggest a default stem map filename derived from the input
        suggested = ""
        if self.uav_lineEdit.text().strip():
            suggested = self._suggest_stem_map_output(self.uav_lineEdit.text().strip())

        file_path, _ = QFileDialog.getSaveFileName(
            self,
            "Select Location And Name For Stem Map Output",
            suggested,
            "TIFF Files (*.tiff *.tif);;All Files (*)",
            options=options,
        )
        if file_path:
            # Normalize to '<base>_stem_map.tiff' and update derived outputs
            self.output_lineEdit_stem.setText(file_path)

    def set_path_from_line_edit(self):
        # Input path: always re-read from the visible field (the source of
        # truth). The user may have typed it, or a layer was picked from the
        # QgsMapLayerComboBox — either way the cached self.uav_path from the
        # file dialog is not authoritative. Empty here == the "No such file"
        # crash in rasterio, so we capture it now and validate in run_process.
        self.uav_path = self.uav_lineEdit.text().strip()

        # Output stem map path is OPTIONAL. If the user left it empty we write
        # to a temp dir and offer an Export afterwards, so a run "just works"
        # without forcing a path up front. (An empty path otherwise reaches
        # IO.atomic_tmp_path as Path("") and crashes with the cryptic
        # "PosixPath('.') has an empty name" deep in the prediction phase.)
        stem_field = self.output_lineEdit_stem.text().strip()
        self._last_output_is_temp = not bool(stem_field)
        if not stem_field:
            stem_field = self._temp_stem_map_base()
        stem_out = self._normalize_stem_map_output(stem_field)
        self.stem_path = stem_out

        # Derived vector output: '<base>_detected_stems.gpkg'
        base = self._stem_base_from_stem_map(stem_out)
        gpkg_path = f"{base}_detected_stems.gpkg" if base else ""

        # Only pass the gpkg path for the selected mode.
        if self.process_type != "Stems":
            self.trees_path = gpkg_path
        else:
            self.trees_path = ""

        # Remember what this run will produce, for the Export action.
        self._last_outputs = [p for p in (self.stem_path, self.trees_path) if p]

        # Keep UI in sync (read-only display)
        try:
            self.output_lineEdit_trees.setText(gpkg_path if self.output_checkBox_trees.isChecked() or self.output_checkBox_nodes.isChecked() else "")
        except Exception:
            pass

    def _winmol_tmp_dir(self) -> str:
        """A temp area for outputs when no output path is given. Under the QGIS
        profile so it's discoverable, falling back to the system temp dir."""
        base = None
        try:
            from qgis.core import QgsApplication
            base = QgsApplication.qgisSettingsDirPath()
        except Exception:
            base = None
        root = os.path.join(base, "winmol", "tmp") if base else None
        if not root:
            import tempfile
            root = os.path.join(tempfile.gettempdir(), "winmol")
        os.makedirs(root, exist_ok=True)
        return root

    def _temp_stem_map_base(self) -> str:
        """Unique base path for a temp stem map: '<tmp>/<input>_<id>'.
        _normalize_stem_map_output appends '_stem_map.tiff'."""
        import uuid
        stem = Path(self.uav_path).stem if self.uav_path else "winmol"
        return os.path.join(self._winmol_tmp_dir(),
                            f"{stem}_{uuid.uuid4().hex[:8]}")

    def _suggest_stem_map_output(self, uav_path: str) -> str:
        """Derive default stem map output path from input image path."""
        try:
            p = Path(uav_path)
            base = str(p.with_suffix(""))
            return f"{base}_stem_map.tiff"
        except Exception:
            return ""

    def _normalize_stem_map_output(self, value: str) -> str:
        """Ensure stem map output ends with '_stem_map.tiff'.

        Users may type a base path, a .tif/.tiff, or even a .gpkg path.
        We normalize to the required stem map filename convention.
        """
        if not value:
            return ""

        # Strip quotes (Windows copy/paste)
        value = value.strip().strip('"').strip("'")

        p = Path(value)

        # If user picked a gpkg, treat it as base and convert to stem map
        if p.suffix.lower() == ".gpkg":
            p = p.with_suffix("")

        # If user picked a tif/tiff, remove extension for base handling
        if p.suffix.lower() in (".tif", ".tiff"):
            p = p.with_suffix("")

        s = str(p)

        # Remove known suffixes if already present
        for suf in ("_stem_map", "_detected_stems"):
            if s.lower().endswith(suf):
                s = s[: -len(suf)]
                break

        # Final normalized stem map
        return f"{s}_stem_map.tiff"

    def _stem_base_from_stem_map(self, stem_map_path: str) -> str:
        """Return the common base (without suffixes/extensions)."""
        if not stem_map_path:
            return ""
        p = Path(stem_map_path)
        s = str(p.with_suffix(""))
        if s.lower().endswith("_stem_map"):
            s = s[:-len("_stem_map")]
        return s

    def _update_derived_output_fields(self):
        """Update derived gpkg output fields whenever stem output changes."""
        if getattr(self, "_updating_output_fields", False):
            return
        try:
            self._updating_output_fields = True

            stem_out = self._normalize_stem_map_output(self.output_lineEdit_stem.text().strip())
            # If normalization changes the visible text, update it (keeps UI consistent)
            if stem_out and self.output_lineEdit_stem.text().strip() != stem_out:
                self.output_lineEdit_stem.setText(stem_out)

            base = self._stem_base_from_stem_map(stem_out)
            gpkg_path = f"{base}_detected_stems.gpkg" if base else ""

            # Show derived gpkg paths (read-only)
            self.output_lineEdit_trees.setText(gpkg_path if self.output_checkBox_trees.isChecked() else "")
        finally:
            self._updating_output_fields = False

    def check_uav_input_exists(self, file_path):
        # Check if the file is already loaded in QGIS
        loaded_layers = QgsProject.instance().mapLayers().values()
        if any(layer.source().split("|")[0] == file_path for layer in loaded_layers):
            matching_layers = [
                layer for layer in loaded_layers if layer.source().split("|")[0] == file_path
            ]
            # Remove the matching layers
            for layer in matching_layers:
                QgsProject.instance().removeMapLayer(layer.id())

    def file_dialog_trees(self):
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getSaveFileName(
            self,
            "Select location and name for the detected stems.",
            "",
            "All Files (*)",
            options=options,
        )
        if file_path:
            self.output_lineEdit_trees.setText(file_path)
            self.trees_path = self.output_lineEdit_trees.text()

    def checkbox_changed_stem(self, state):
        is_checked = state == 2
        self.output_lineEdit_stem.setEnabled(is_checked)
        self.output_toolButton_stem.setEnabled(is_checked)
        self.apply_style_to_line_edit(self.output_lineEdit_stem, is_checked)

        # Stem map is the base output. If disabled, also disable higher modes.
        self.output_checkBox_trees.setEnabled(is_checked)
        if not is_checked:
            self.output_checkBox_trees.setChecked(False)
            self.output_checkBox_nodes.setChecked(False)
            self.output_checkBox_nodes.setEnabled(False)

        self._update_derived_output_fields()

    def checkbox_changed_trees(self, state):
        is_checked = state == 2

        # Trees/Nodes outputs are derived; prevent manual path editing.
        self.output_checkBox_nodes.setEnabled(is_checked)
        if not is_checked:
            self.output_checkBox_nodes.setChecked(False)

        self._update_derived_output_fields()

    def checkbox_changed_nodes(self, state):
        # Nodes output is derived; prevent manual path editing.
        _ = state  # kept for signal signature compatibility
        self._update_derived_output_fields()

    def set_selected_model(self):
        selected_text = self.model_comboBox.currentText().strip()
        if selected_text == "Custom":
            self.model_path = self.model_lineEdit.text().strip()
            return

        if selected_text:
            self.model_path = os.path.join(
                self.models_dir, f"{selected_text}.onnx")
        else:
            self.model_path = ""

    def set_selected_process_type(self):
        stem_checked = self.output_checkBox_stem.isChecked()
        trees_checked = self.output_checkBox_trees.isChecked()
        nodes_checked = self.output_checkBox_nodes.isChecked()

        if nodes_checked:
            self.process_type = "Nodes"
        elif trees_checked:
            self.process_type = "Trees"
        elif stem_checked:
            self.process_type = "Stems"
        else:
            self.process_type = "Stems"

    def save_temp_layer(self, layer, layer_name: str, add_to_legend: bool = True):
        """
        Add a raster/vector layer to the current QGIS project as a *temporary* layer.

        Parameters
        ----------
        layer : QgsMapLayer | str
            Either an already-created QgsRasterLayer/QgsVectorLayer, or a datasource
            path/URI (e.g. 'C:/x/out.gpkg|layername=stems', 'C:/x/out.tif').
        layer_name : str
            Name to assign in the QGIS layer tree.
        add_to_legend : bool
            Whether the layer should appear in the layer tree (default True).

        Returns
        -------
        QgsMapLayer | None
        """
        if layer is None:
            return None

        # Allow passing a path/URI instead of a QgsMapLayer object
        if isinstance(layer, str):
            src = layer.strip()
            if not src:
                return None

            # Decide raster vs vector by extension of the *file* part (before '|')
            file_part = src.split("|", 1)[0]
            ext = os.path.splitext(file_part)[1].lower()

            if ext in (".tif", ".tiff", ".vrt", ".asc", ".img"):
                layer = QgsRasterLayer(src, layer_name or os.path.basename(file_part), "gdal")
            else:
                layer = QgsVectorLayer(src, layer_name or os.path.basename(file_part), "ogr")

        # Validate
        if not layer or not layer.isValid():
            print(f"save_temp_layer(): invalid layer for '{layer_name}'")
            return None

        if layer_name:
            layer.setName(layer_name)

        project = QgsProject.instance()

        # Avoid duplicates if it’s already in the project
        if layer.id() in project.mapLayers():
            return layer

        project.addMapLayer(layer, add_to_legend)
        return layer

    def apply_style_to_line_edit(self, line_edit, is_checked):
        # Enable or disable the QLineEdit based on the checkbox state
        line_edit.setEnabled(is_checked)

        # Set the stylesheet to gray out the QLineEdit when it is disabled
        if not is_checked:
            line_edit.setStyleSheet("")
        else:
            line_edit.setStyleSheet(
                "QLineEdit { background-color: rgb(255, 255, 255) }"
            )

    def cancel_process(self):
        # Actually terminate the child process, not just the thread signal.
        # Guard on _run_active: after a run ends the worker is deleteLater'd,
        # so calling into it would hit a deleted C++ object.
        if self._run_active and self.worker:
            self.update_output_log("Cancelling…")
            try:
                self.worker.cancel()
            except RuntimeError:
                pass

    def close_application(self):
        print("Closing application")
        self.close()

    def closeEvent(self, event):
        # Never let a running background QThread be destroyed while its OS
        # thread is alive — that qFatals QGIS. Stop/park threads first.
        self._shutdown_threads()
        super().closeEvent(event)

    def _shutdown_threads(self):
        """Stop background threads (inference + env build) so the dialog and
        its parentless QThreads can be torn down safely. Call this from the
        plugin's unload() too, before QGIS drops the dialog reference."""
        # Inference: cancelling terminates the child process, so the thread's
        # read loop returns quickly and the thread can be waited out.
        if self._run_active and self.worker is not None:
            try:
                self.worker.cancel()
            except (RuntimeError, AttributeError):
                pass
        self._reap_thread(self.thread, self.worker)
        # Env build: request cancel; network reads are timeout-bounded, but a
        # pip install mid-flight can't be interrupted, so it may get parked.
        if self._env_worker is not None:
            try:
                self._env_worker.cancel()
            except (RuntimeError, AttributeError):
                pass
        self._reap_thread(self._env_thread, self._env_worker)

    def _reap_thread(self, thread, worker):
        """Quit + wait a bounded time for a QThread. If it is still running
        (e.g. pip mid-install), park it in _ALIVE_BG so it is never GC'd while
        running (which would qFatal); it self-evicts when it finishes."""
        if thread is None:
            return
        try:
            if not thread.isRunning():
                return
            thread.quit()
            if thread.wait(8000):
                return
            _ALIVE_BG.add(thread)
            if worker is not None:
                _ALIVE_BG.add(worker)

            def _evict(t=thread, w=worker):
                _ALIVE_BG.discard(t)
                _ALIVE_BG.discard(w)
            thread.finished.connect(_evict)
        except RuntimeError:
            pass

    def run_process(self):
        # Guard against re-entry: a second Run while one is live would reassign
        # self.thread and destroy a still-running QThread -> Qt qFatal aborts
        # the whole QGIS process. (This is what crashed QGIS.)
        if self._run_active:
            QtWidgets.QMessageBox.information(
                self, "WINMOL Analyzer",
                "A run is already in progress. Wait for it to finish, or press "
                "Cancel, before starting another.")
            return

        # Path to the Python script
        path_dirname = os.path.dirname(__file__)
        script_path = os.path.join(path_dirname, "winmol_run.py")

        # set chosen parameters
        self.set_selected_model()

        if not self.model_path:
            QtWidgets.QMessageBox.warning(self, "WINMOL Analyzer", "No model selected.")
            return
        if self.model_comboBox.currentText().strip() != "Custom" and not os.path.exists(self.model_path):
            QtWidgets.QMessageBox.warning(
                self,
                "WINMOL Analyzer",
                f"Selected model file was not found:\n{self.model_path}\n\n"
                "Tip: restart QGIS to let the plugin download models, or pick a Custom model file.",
            )
            return

        self.set_selected_process_type()
        self.set_path_from_line_edit()

        # Validate the input BEFORE launching the subprocess: an empty or
        # missing path otherwise surfaces as an opaque rasterio
        # "No such file or directory" deep in winmol_run.py.
        if not self.uav_path:
            QtWidgets.QMessageBox.warning(
                self, "WINMOL Analyzer",
                "No input GeoTiff selected. Pick a file, type a path, or "
                "choose a loaded raster layer.")
            return
        if not os.path.exists(self.uav_path):
            QtWidgets.QMessageBox.warning(
                self, "WINMOL Analyzer",
                f"Input GeoTiff was not found:\n{self.uav_path}")
            return
        # The stem map raster is always written; an empty output path crashes
        # the prediction phase. set_path_from_line_edit auto-derives it from the
        # input, so this only trips if that derivation somehow failed.
        if not self.stem_path or Path(self.stem_path).name == "":
            QtWidgets.QMessageBox.warning(
                self, "WINMOL Analyzer",
                "No output path is set and none could be derived from the "
                "input. Set an output stem map path.")
            return

        # check if uav image is loaded in qgis
        self.check_uav_input_exists(self.stem_path)

        if self.trees_path:
            # unload final gpkg layers
            self.check_uav_input_exists(self.trees_path)

            # unload *_new.gpkg layers too (fallback filename)
            p = Path(self.trees_path)
            alt = str(p.with_name(p.stem + "_new.gpkg"))
            self.check_uav_input_exists(alt)

        # Run winmol_run.py in the resolved compute environment; if it isn't
        # ready, let the user pick/create one right here (no restart).
        if not self._env_ready():
            self.choose_environment()
        if not self._env_ready():
            return
        command = [
            self.python_exe,
            "-u",
            script_path,
            self.model_path,
            self.uav_path,
            self.stem_path,
            self.trees_path,
            self.process_type,
        ]

        # Switch to the log tab in the QTabWidget
        self.log_widget.setCurrentIndex(1)

        # clear the output log
        self.output_log.clear()

        self.update_output_log("Starting the process...")

        # for debugging run subprocess directly
        # import subprocess
        # process = subprocess.run(
        #     command,
        #     capture_output=True,
        #     text=True
        # )
        # print(process.stdout)
        # print(process.stderr)
        # self.update_output_log(process.stdout)
        # self.update_output_log(process.stderr)

        # Run this part for responsive GUI
        print("Starting the process...")
        try:
            self.thread = QThread()
            self.worker = Worker(command)
            self.worker.moveToThread(self.thread)
            self.worker.progress_signal.connect(self.update_progress)
            self.thread.started.connect(self.worker.run_process)
            # layers load ONLY on success; failures surface in the log/dialog
            self.worker.succeeded.connect(self.load_layers_to_session)
            self.worker.error.connect(self.handle_process_error)
            self.worker.finished.connect(self.thread.quit)
            self.worker.finished.connect(self.worker.deleteLater)
            self.thread.finished.connect(self.thread.deleteLater)
            self.thread.finished.connect(self._on_run_finished)
            self.worker.update_signal.connect(self.update_output_log)
            # Mark active + lock the Run and Environment buttons BEFORE
            # starting, so a second click can't reassign self.thread (abort) or
            # start a competing env build.
            self._run_active = True
            for _b in ("run_button", "env_button"):
                _w = getattr(self, _b, None)
                if _w is not None:
                    try:
                        _w.setEnabled(False)
                    except Exception:
                        pass
            self.thread.start()
        # catch out of memory error
        except MemoryError:
            self._run_active = False
            try:
                self.run_button.setEnabled(True)
            except Exception:
                pass
            self.worker.update_signal.disconnect(self.update_output_log)
            self.update_output_log(
                "The operation ran out of memory. "
                "Please free up some memory and "
                "try again."
            )
            self.check_swap_memory()

    def update_output_log(self, text):
        # Update your QPlainTextEdit with the output
        self.output_log.appendPlainText(text)

    def handle_process_error(self, message):
        """Show a failure instead of silently loading empty/absent layers."""
        self.update_output_log(message)
        try:
            QtWidgets.QMessageBox.warning(self, "WINMOL Analyzer", message)
        except Exception:
            pass

    def _on_run_finished(self):
        """Runs on thread.finished (success OR failure): clear the active flag
        so the next run can safely build a fresh thread, and re-enable the UI.
        Offers Export if the run produced outputs on disk."""
        self._run_active = False
        # Re-enable Run, and the Environment button unless an env build is in
        # flight (its own handlers manage it then).
        for _b, _cond in (("run_button", True),
                          ("env_button", self._env_thread is None)):
            _w = getattr(self, _b, None)
            if _w is not None and _cond:
                try:
                    _w.setEnabled(True)
                except Exception:
                    pass
        produced = any(os.path.exists(p) for p in self._last_outputs)
        self._set_export_enabled(produced)
        if produced and self._last_output_is_temp:
            self.update_output_log(
                "Outputs were written to a temp folder. Use 'Export…' to save "
                "them to a permanent location.")

    def _set_export_enabled(self, on):
        btn = getattr(self, "export_button", None)
        if btn is not None:
            try:
                btn.setEnabled(bool(on))
            except Exception:
                pass

    def export_results(self):
        """Copy the last run's outputs (stem map + any gpkg) to a folder the
        user chooses. Lets runs default to a temp dir yet still be saved."""
        import shutil
        outputs = [p for p in self._last_outputs if os.path.exists(p)]
        if not outputs:
            QtWidgets.QMessageBox.information(
                self, "WINMOL Analyzer",
                "No results to export yet. Run an analysis first.")
            return
        target_dir = QFileDialog.getExistingDirectory(
            self, "Export results to folder", "")
        if not target_dir:
            return
        copied = []
        for src in outputs:
            try:
                dst = os.path.join(target_dir, os.path.basename(src))
                shutil.copy2(src, dst)
                copied.append(dst)
                # bring along a sidecar stats file if the raster has one
                sidecar = src + ".aux.xml"
                if os.path.exists(sidecar):
                    shutil.copy2(sidecar, dst + ".aux.xml")
            except Exception as exc:
                self.update_output_log(f"Export failed for {src}: {exc}")
        if copied:
            self.update_output_log("Exported:\n" + "\n".join(copied))
            QtWidgets.QMessageBox.information(
                self, "WINMOL Analyzer",
                f"Exported {len(copied)} file(s) to:\n{target_dir}")

    # --- compute-environment selection --------------------------------------

    def _add_custom_controls(self):
        """Add controls not present in the .ui: a persistent 'Environment…'
        button and a QGIS layer selector for the input raster. Defensive — if
        a widget can't be placed (e.g. an older/newer QGIS gui API), the file
        picker and on-open env prompt still work."""
        # Persistent Environment button (top bar, always visible).
        try:
            bar = QtWidgets.QWidget(self)
            h = QtWidgets.QHBoxLayout(bar)
            h.setContentsMargins(0, 0, 0, 0)
            self.env_button = QtWidgets.QPushButton("Environment…", bar)
            self.env_button.setToolTip(
                "Choose or create the Python environment that runs the "
                "analysis (a conda env / venv with onnxruntime + geo libs).")
            self.env_button.clicked.connect(self.choose_environment)
            self.env_status_label = QtWidgets.QLabel(bar)
            self.export_button = QtWidgets.QPushButton("Export…", bar)
            self.export_button.setToolTip(
                "Save the last run's outputs (stem map / stems) to a folder. "
                "Runs without an output path go to a temp folder until "
                "exported.")
            self.export_button.setEnabled(False)
            self.export_button.clicked.connect(self.export_results)
            h.addWidget(self.env_button)
            h.addWidget(self.env_status_label, 1)
            h.addWidget(self.export_button)
            top = getattr(self, "verticalLayout_7", None) or self.layout()
            if top is not None:
                top.insertWidget(0, bar)
            self._refresh_env_status()
        except Exception as exc:                       # pragma: no cover - GUI
            print("WINMOL: could not add Environment button:", exc)

        # Input raster layer selector (pick a layer already loaded in QGIS).
        try:
            from qgis.gui import QgsMapLayerComboBox
            from qgis.core import QgsMapLayerProxyModel
            self.uav_layer_combo = QgsMapLayerComboBox(self)
            self.uav_layer_combo.setFilters(QgsMapLayerProxyModel.RasterLayer)
            self.uav_layer_combo.setAllowEmptyLayer(True)
            self.uav_layer_combo.setToolTip(
                "Or pick a raster layer already loaded in QGIS")
            # Connect AFTER construction so the combo's initial auto-selection
            # doesn't fire into our slot; then force 'empty' so we never
            # clobber a typed path when the dialog opens.
            self.uav_layer_combo.layerChanged.connect(
                self._on_uav_layer_changed)
            row = QtWidgets.QWidget(self)
            hr = QtWidgets.QHBoxLayout(row)
            hr.setContentsMargins(0, 0, 0, 0)
            hr.addWidget(QtWidgets.QLabel("Loaded layer:", row))
            hr.addWidget(self.uav_layer_combo, 1)
            grid = getattr(self, "gridLayout", None)
            if grid is not None and hasattr(grid, "addWidget"):
                grid.addWidget(row, 3, 0, 1, 3)
            elif getattr(self, "verticalLayout_4", None) is not None:
                self.verticalLayout_4.insertWidget(1, row)
            try:
                self.uav_layer_combo.setLayer(None)
            except Exception:
                pass
        except Exception as exc:                       # pragma: no cover - GUI
            print("WINMOL: could not add layer selector:", exc)

    def _on_uav_layer_changed(self, layer):
        """A raster layer was chosen: use its source as the input path."""
        try:
            if layer is None or not layer.isValid():
                return
            # Strip GDAL subdataset/URI decorations (e.g. 'path|layername').
            src = layer.source().split("|")[0]
            if src:
                self.uav_lineEdit.setText(src)
                self.uav_path = src
                self.check_input_file()
        except Exception:                              # pragma: no cover - GUI
            pass

    def _refresh_env_status(self):
        lbl = getattr(self, "env_status_label", None)
        if lbl is None:
            return
        if self._env_ready():
            lbl.setText(f"Env: {self.python_exe}")
        else:
            lbl.setText("Env: not set — click Environment…")

    def _env_ready(self):
        return bool(self.python_exe) and os.path.exists(self.python_exe)

    def _set_python(self, exe):
        """Persist the chosen interpreter and use it immediately (no restart)."""
        self.python_exe = exe
        QgsSettings().setValue(installer.QSETTINGS_PYTHON_KEY, exe)
        self._refresh_env_status()

    def choose_environment(self):
        """Interactive picker: use an existing interpreter (venv/conda) or
        create one. Updates the interpreter live — no QGIS restart needed."""
        box = QtWidgets.QMessageBox(self)
        box.setWindowTitle("WINMOL compute environment")
        box.setText(
            "WINMOL needs a Python environment (onnxruntime + geo libraries) "
            "to run the analysis.\n\nChoose an existing interpreter (a conda "
            "env or venv), or let WINMOL create one.")
        b_choose = box.addButton("Choose interpreter…",
                                 QtWidgets.QMessageBox.AcceptRole)
        b_create = box.addButton("Create for me",
                                 QtWidgets.QMessageBox.ActionRole)
        box.addButton("Cancel", QtWidgets.QMessageBox.RejectRole)
        box.exec_() if hasattr(box, "exec_") else box.exec()
        clicked = box.clickedButton()
        if clicked == b_choose:
            self._choose_interpreter()
        elif clicked == b_create:
            self._create_environment()

    def _choose_interpreter(self):
        exe, _ = QFileDialog.getOpenFileName(
            self, "Select a Python interpreter (e.g. <env>/bin/python)", "")
        if not exe:
            return
        ver = installer._python_version(exe)
        if not (installer.MIN_PY <= ver <= installer.MAX_PY):
            QtWidgets.QMessageBox.warning(
                self, "Unsupported Python",
                f"{exe} is Python {ver[0]}.{ver[1]}; WINMOL needs "
                f"{installer.MIN_PY[0]}.{installer.MIN_PY[1]}-"
                f"{installer.MAX_PY[0]}.{installer.MAX_PY[1]}.")
            return
        if installer._has_compute_deps(exe):
            self._set_python(exe)
            self.update_output_log(f"Using interpreter: {exe}")
            return
        reply = QtWidgets.QMessageBox.question(
            self, "Missing dependencies",
            f"{exe} lacks WINMOL dependencies (onnxruntime/rasterio/"
            "geopandas). Install them into it now?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        if reply == QtWidgets.QMessageBox.Yes:
            self._pip_install_into(exe)

    def _pip_install_into(self, exe):
        """Install the deps into a user-picked interpreter — on the worker
        thread. Running pip inline here froze QGIS (no repaint, 'not
        responding') for the whole multi-minute install."""
        self._start_env_worker(
            f"Installing dependencies into {exe}. This can take several "
            "minutes; progress appears below…", target_exe=exe)

    def _create_environment(self):
        """Build the compute environment (download Python 3.11 if needed, make
        the venv, pip-install deps) on a background thread so QGIS stays
        responsive. Progress streams to the log."""
        self._start_env_worker(
            "Setting up the WINMOL environment (Python 3.11 + onnxruntime + "
            "geo libraries). First run downloads a few hundred MB and can "
            "take several minutes; progress appears below…")

    def _start_env_worker(self, banner, target_exe=None):
        """Run an environment build on a QThread, streaming progress into the
        same log panel the prediction run writes to."""
        if self._env_thread is not None:
            self.update_output_log("Environment setup is already running…")
            return
        plugin_dir = os.path.dirname(os.path.abspath(__file__))
        self.update_output_log(banner)
        try:
            self.log_widget.setCurrentIndex(1)   # show the log tab
        except Exception:
            pass
        from .tasks_threads import EnvSetupWorker
        self._env_thread = QThread()
        self._env_worker = EnvSetupWorker(plugin_dir, target_exe=target_exe)
        self._env_worker.moveToThread(self._env_thread)
        self._env_thread.started.connect(self._env_worker.run)
        self._env_worker.log.connect(self.update_output_log)
        self._env_worker.done.connect(self._on_env_ready)
        self._env_worker.failed.connect(self._on_env_failed)
        # Quit the thread and drop the worker once it finishes either way.
        self._env_worker.done.connect(self._env_thread.quit)
        self._env_worker.failed.connect(self._env_thread.quit)
        self._env_worker.done.connect(self._env_worker.deleteLater)
        self._env_worker.failed.connect(self._env_worker.deleteLater)
        self._env_thread.finished.connect(self._env_thread.deleteLater)
        self._env_thread.finished.connect(self._clear_env_thread)
        # Lock the buttons that would race the build.
        for _b in ("env_button", "run_button"):
            _w = getattr(self, _b, None)
            if _w is not None:
                try:
                    _w.setEnabled(False)
                except Exception:
                    pass
        self._env_thread.start()

    def _clear_env_thread(self):
        """thread.finished: drop refs so a later build makes a fresh thread,
        and re-enable the env button."""
        self._env_thread = None
        self._env_worker = None
        _w = getattr(self, "env_button", None)
        if _w is not None:
            try:
                _w.setEnabled(True)
            except Exception:
                pass

    def _on_env_ready(self, exe):
        if exe:
            self._set_python(exe)
            self.update_output_log("Environment ready.")
        else:
            self.update_output_log(
                "Environment setup finished but returned no interpreter.")
        # Only re-enable Run if no inference run is currently active.
        _w = getattr(self, "run_button", None)
        if _w is not None and not self._run_active:
            try:
                _w.setEnabled(True)
            except Exception:
                pass

    def _on_env_failed(self, msg):
        self.update_output_log(f"Could not create environment: {msg}")
        _w = getattr(self, "run_button", None)
        if _w is not None and not self._run_active:
            try:
                _w.setEnabled(True)
            except Exception:
                pass
        QtWidgets.QMessageBox.warning(
            self, "WINMOL environment",
            f"Could not create an environment automatically:\n{msg}\n\n"
            "Use 'Choose interpreter…' to point at an existing conda "
            "env or venv instead.")

    def load_layers_to_session(self):
        """Load outputs after processing finishes.

        Legacy output was GeoJSON:
            (*_stems.geojson, *_nodes.geojson, *_vectors.geojson).
        Newer versions write GeoPackage:
            (*.gpkg) with layers: stems, nodes, vectors.

        This method supports both.
        """

        print("Loading output layers into QGIS session...")
        self.load_raster(self.stem_path)
        gpkg = self._resolve_output_gpkg(self.trees_path)

        if not gpkg:
            print("No output GeoPackage found; skipping vector layer loading.")
            return

        # Trees output: stems only
        if self.output_checkBox_trees.isChecked():
            self.load_gpkg_layers(gpkg, ["stems"])

        # Nodes output: stems + nodes + vectors
        if self.output_checkBox_nodes.isChecked():
            self.load_gpkg_layers(gpkg, ["stems", "vectors", "nodes"])

    def _resolve_output_gpkg(self, path_prefix: str):
        """Return an existing output GeoPackage path for a given prefix.

        IO.write_*_to_gpkg uses Path(prefix).with_suffix('.gpkg').
        On Windows/QGIS, the target file may be locked;
        in that case IO writes '<name>_new.gpkg'.
        """
        if not path_prefix:
            return None

        p = Path(path_prefix)

        # Normal target
        gpkg = str(p.with_suffix(".gpkg"))
        if os.path.exists(gpkg):
            return gpkg

        # Locked target fallback written by _safe_finalize_gpkg()
        gpkg_new = str(Path(gpkg).with_name(Path(gpkg).stem + "_new.gpkg"))
        if os.path.exists(gpkg_new):
            return gpkg_new

        # Any gpkg with the same prefix (e.g. foo_new.gpkg, foo_001.gpkg)
        candidates = sorted(glob.glob(str(p.parent / (p.stem + "*.gpkg"))))
        return candidates[0] if candidates else None

    def load_gpkg_layers(self, gpkg_path: str, layer_names):
        """Load multiple layers from a GeoPackage into the QGIS project."""
        for ln in layer_names:
            self.load_gpkg_layer(gpkg_path, ln)

    def load_gpkg_layer(self, gpkg_path: str, layer_name: str):
        name = f"{Path(gpkg_path).stem}_{layer_name}"
        uri = f"{gpkg_path}|layername={layer_name}"
        vector_layer = QgsVectorLayer(uri, name, "ogr")
        if not vector_layer.isValid():
            print(f"Error loading GeoPackage layer '{layer_name}' from {gpkg_path}")
            return
        QgsProject.instance().addMapLayer(vector_layer)

    def load_raster(self, path):
        # Check if the path ends with ".tiff" (case-insensitive)
        if not path.lower().endswith(".tiff"):
            path = str(Path(path).with_suffix(".tiff"))
        # Extract the base name of the input image file
        name = os.path.splitext(os.path.basename(path))[0]
        # Load raster layer
        raster_layer = QgsRasterLayer(path, name, "gdal")
        # Check if the layer was loaded successfully
        if not raster_layer.isValid():
            print(f"Error loading raster layer from {path}")
            return

        # Add the raster layer to the current QGIS project
        QgsProject.instance().addMapLayer(raster_layer)
        print(f"Raster layer loaded successfully from {path}")

    def load_geojson(self, path):
        # Extract the base name of the input image file
        name = os.path.splitext(os.path.basename(path))[0]
        # Load vector layer
        vector_layer = QgsVectorLayer(path, name, "ogr")
        if not vector_layer.isValid():
            print(f"Error loading vector layer from {path}")
        else:
            # Add the vector layer to the map
            QgsProject.instance().addMapLayer(vector_layer)

    def update_progress(self, value):
        self.progress_bar.setValue(value)

    def check_swap_memory(self):
        # psutil is optional in QGIS's Python (see the guarded import at the
        # top); without it, just skip the advisory rather than raising
        # AttributeError on top of the MemoryError that got us here.
        if psutil is None:
            return
        swap = psutil.swap_memory()
        ram = psutil.virtual_memory()

        # Convert bytes to GB
        swap_in_gb = swap.total / (1024**3)
        ram_in_gb = ram.total / (1024**3)

        if swap_in_gb < ram_in_gb:
            self.update_output_log(
                f"Warning: Your swap memory ({swap_in_gb} GB) is less than your physical memory ({ram_in_gb} GB). "
                "It is recommended to increase your swap memory to at least be equal to your physical memory."
            )
